/*
reg  page 362
dio  page 65
exit page 89
adc  page 230
timer1 page 92
*/
#ifndef _ATMEGA128_REG_H 
#define _ATMEGA128_REG_H

#include <stdint.h>

#define UCSR1C_Reg   *((volatile uint8_t*)0x9D)
#define UDR1_Reg   *((volatile uint8_t*)0x9C)
#define UCSR1A_Reg   *((volatile uint8_t*)0x9B)
#define UCSR1B_Reg   *((volatile uint8_t*)0x9A)
#define UBRR1L_Reg   *((volatile uint8_t*)0x99)
#define UBRR1H_Reg   *((volatile uint8_t*)0x98)
#define UCSR0C_Reg   *((volatile uint8_t*)0x95)
#define UBRR0H_Reg   *((volatile uint8_t*)0x90)
#define TCCR3C_Reg   *((volatile uint8_t*)0x8C)
#define TCCR3A_Reg   *((volatile uint8_t*)0x8B)
#define TCCR3B_Reg   *((volatile uint8_t*)0x8A)
#define TCNT3H_Reg   *((volatile uint8_t*)0x89)
#define TCNT3L_Reg   *((volatile uint8_t*)0x88)
#define OCR3AH_Reg   *((volatile uint8_t*)0x87)
#define OCR3AL_Reg   *((volatile uint8_t*)0x86)
#define OCR3BH_Reg   *((volatile uint8_t*)0x85)
#define OCR3BL_Reg   *((volatile uint8_t*)0x84)
#define OCR3CH_Reg   *((volatile uint8_t*)0x83)
#define OCR3CL_Reg   *((volatile uint8_t*)0x82)
#define ICR3H_Reg   *((volatile uint8_t*)0x81)
#define ICR3L_Reg   *((volatile uint8_t*)0x80)
#define ETIMSK_Reg   *((volatile uint8_t*)0x7D)
#define ETIFR_Reg   *((volatile uint8_t*)0x7C)
#define TCCR1C_Reg   *((volatile uint8_t*)0x7A)
#define OCR1CH_Reg   *((volatile uint8_t*)0x79)
#define OCR1CL_Reg   *((volatile uint8_t*)0x78)
#define TWCR_Reg   *((volatile uint8_t*)0x74)
#define TWDR_Reg   *((volatile uint8_t*)0x73)
#define TWAR_Reg   *((volatile uint8_t*)0x72)
#define TWSR_Reg   *((volatile uint8_t*)0x71)
#define TWBR_Reg   *((volatile uint8_t*)0x70)
#define OSCCAL_Reg   *((volatile uint8_t*)0x6F)
#define XMCRA_Reg   *((volatile uint8_t*)0x6D)
#define XMCRB_Reg   *((volatile uint8_t*)0x6C)
#define EICRA_Reg   *((volatile uint8_t*)0x6A)
#define SPMCSR_Reg   *((volatile uint8_t*)0x68)
#define PORTG_Reg   *((volatile uint8_t*)0x65)
#define DDRG_Reg   *((volatile uint8_t*)0x64)
#define PING_Reg   *((volatile uint8_t*)0x63)
#define PORTF_Reg   *((volatile uint8_t*)0x62)
#define DDRF_Reg   *((volatile uint8_t*)0x61)
#define SREG_Reg   *((volatile uint8_t*)0x5F)
#define SPH_Reg   *((volatile uint8_t*)0x5E)
#define SPL_Reg   *((volatile uint8_t*)0x5D)
#define XDIV_Reg   *((volatile uint8_t*)0x5C)
#define RAMPZ_Reg   *((volatile uint8_t*)0x5B)
#define EICRB_Reg   *((volatile uint8_t*)0x5A)
#define EIMSK_Reg   *((volatile uint8_t*)0x59)
#define EIFR_Reg   *((volatile uint8_t*)0x58)
#define TIMSK_Reg   *((volatile uint8_t*)0x57)
#define TIFR_Reg   *((volatile uint8_t*)0x56)
#define MCUCR_Reg   *((volatile uint8_t*)0x55)
#define MCUCSR_Reg   *((volatile uint8_t*)0x54)
#define TCCR0_Reg   *((volatile uint8_t*)0x53)
#define TCNT0_Reg   *((volatile uint8_t*)0x52)
#define OCR0_Reg   *((volatile uint8_t*)0x51)
#define ASSR_Reg   *((volatile uint8_t*)0x50)
#define TCCR1A_Reg   *((volatile uint8_t*)0x4F)
#define TCCR1B_Reg   *((volatile uint8_t*)0x4E)
#define TCNT1H_Reg   *((volatile uint8_t*)0x4D)
#define TCNT1L_Reg   *((volatile uint8_t*)0x4C)
#define OCR1AH_Reg   *((volatile uint8_t*)0x4B)
#define OCR1AL_Reg   *((volatile uint8_t*)0x4A)
#define OCR1BH_Reg   *((volatile uint8_t*)0x49)
#define OCR1BL_Reg   *((volatile uint8_t*)0x48)
#define ICR1H_Reg   *((volatile uint8_t*)0x47)
#define ICR1L_Reg   *((volatile uint8_t*)0x46)
#define TCCR2_Reg   *((volatile uint8_t*)0x45)
#define TCNT2_Reg   *((volatile uint8_t*)0x44)
#define OCR2_Reg   *((volatile uint8_t*)0x43)
#define OCDR_Reg   *((volatile uint8_t*)0x42)
#define WDTCR_Reg   *((volatile uint8_t*)0x41)
#define SFIOR_Reg   *((volatile uint8_t*)0x40)
#define EEARH_Reg   *((volatile uint8_t*)0x3F)
#define EEARL_Reg   *((volatile uint8_t*)0x3E)
#define EEDR_Reg   *((volatile uint8_t*)0x3D)
#define EECR_Reg   *((volatile uint8_t*)0x3C)
#define PORTA_Reg   *((volatile uint8_t*)0x3B)
#define DDRA_Reg   *((volatile uint8_t*)0x3A)
#define PINA_Reg   *((volatile uint8_t*)0x39)
#define PORTB_Reg   *((volatile uint8_t*)0x38)
#define DDRB_Reg   *((volatile uint8_t*)0x37)
#define PINB_Reg   *((volatile uint8_t*)0x36)
#define PORTC_Reg   *((volatile uint8_t*)0x35)
#define DDRC_Reg   *((volatile uint8_t*)0x34)
#define PINC_Reg   *((volatile uint8_t*)0x33)
#define PORTD_Reg   *((volatile uint8_t*)0x32)
#define DDRD_Reg   *((volatile uint8_t*)0x31)
#define PIND_Reg   *((volatile uint8_t*)0x30)
#define SPDR_Reg   *((volatile uint8_t*)0x2F)
#define SPSR_Reg   *((volatile uint8_t*)0x2E)
#define SPCR_Reg   *((volatile uint8_t*)0x2D)
#define UDR0_Reg   *((volatile uint8_t*)0x2C)
#define UCSR0A_Reg   *((volatile uint8_t*)0x2B)
#define UCSR0B_Reg   *((volatile uint8_t*)0x2A)
#define UBRR0L_Reg   *((volatile uint8_t*)0x29)
#define ACSR_Reg   *((volatile uint8_t*)0x28)
#define ADMUX_Reg   *((volatile uint8_t*)0x27)
#define ADCSRA_Reg   *((volatile uint8_t*)0x26)
#define ADCH_Reg   *((volatile uint8_t*)0x25)
#define ADCL_Reg   *((volatile uint8_t*)0x24)
#define PORTE_Reg   *((volatile uint8_t*)0x23)
#define DDRE_Reg   *((volatile uint8_t*)0x22)
#define PINE_Reg   *((volatile uint8_t*)0x21)
#define PINF_Reg   *((volatile uint8_t*)0x20)

#endif